[copycat_level]
INDEXED = true

[copycat_user]
INDEXED = true

[copycat_transport]
INDEXED = true

[copycat_action]
INDEXED = true

[copycat_query_type]
INDEXED = true

[copycat_process]
INDEXED = true

[copycat_method]
INDEXED = true

[copycat_status]
INDEXED = true

[copycat_error_type]
INDEXED = true

[copycat_resource]
INDEXED = true
