[script://./bin/copycat.py app]
disabled = false
interval = 10
python.version = python3.9
index = copycat_app
sourcetype = copycat:app

[script://./bin/copycat.py security]
disabled = false
interval = 10
python.version = python3.9
index = copycat_security
sourcetype = copycat:security

[script://./bin/copycat.py network]
disabled = false
interval = 10
python.version = python3.9
index = copycat_network
sourcetype = copycat:network

[script://./bin/copycat.py docker]
disabled = false
interval = 10
python.version = python3.9
index = copycat_docker
sourcetype = copycat:docker

[script://./bin/copycat.py database]
disabled = false
interval = 10
python.version = python3.9
index = copycat_database
sourcetype = copycat:database

[script://./bin/copycat.py webserver]
disabled = false
interval = 10
python.version = python3.9
index = copycat_webserver
sourcetype = copycat:webserver

[script://./bin/copycat.py system]
disabled = false
interval = 10
python.version = python3.9
index = copycat_system
sourcetype = copycat:system

[script://./bin/copycat.py api]
disabled = false
interval = 10
python.version = python3.9
index = copycat_api
sourcetype = copycat:api

[script://./bin/copycat.py error]
disabled = false
interval = 10
python.version = python3.9
index = copycat_error
sourcetype = copycat:error

[script://./bin/copycat.py metrics]
disabled = false
interval = 10
python.version = python3.9
index = copycat_metrics
sourcetype = copycat:metrics
