[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py app]
disabled = false
interval = 10
index = copycat_app
sourcetype = copycat:app
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py security]
disabled = false
interval = 10
index = copycat_security
sourcetype = copycat:security
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py network]
disabled = false
interval = 10
index = copycat_network
sourcetype = copycat:network
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py docker]
disabled = false
interval = 10
index = copycat_docker
sourcetype = copycat:docker
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py database]
disabled = false
interval = 10
index = copycat_database
sourcetype = copycat:database
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py system]
disabled = false
interval = 10
index = copycat_system
sourcetype = copycat:system
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py api]
disabled = false
interval = 10
index = copycat_api
sourcetype = copycat:api
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py error]
disabled = false
interval = 10
index = copycat_error
sourcetype = copycat:error
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9

[script://$SPLUNK_HOME/etc/apps/copycat/bin/copycat.py metrics]
disabled = false
interval = 10
index = copycat_metrics
sourcetype = copycat:metrics
python.required = 3.9, 3.13
# For compatibility with 10.1 and below
python.version = python3.9
