[copycat:app]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:security]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:network]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:docker]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:database]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:webserver]
TIME_FORMAT = %d/%b/%Y:%T %z

[copycat:system]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:api]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:error]
TIME_FORMAT = %Y-%m-%d %T.%f

[copycat:metrics]
TIME_FORMAT = %Y-%m-%d %T.%f
