[copycat:app]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_app_fields = \[(?<level>\w+)\]\s(?<path>(/[\w\.]+)+):\s(?<message>.*)

[copycat:security]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_security_fields = User\s(?<user>[\w\.]+)\slogin\sattempt\sfrom\s(?<ip>\d+\.\d+\.\d+\.\d+)

[copycat:network]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_network_fields = (?<transport>\w+)\s(?<src_ip>\d+\.\d+\.\d+\.\d+):(?<src_port>\d+)\s-\>\s(?<dest_ip>\d+\.\d+\.\d+\.\d+):(?<dest_port>\d+)\s(?<action>\w+)

[copycat:docker]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_docker_fields = Container\s(?<container_name>[\w\-]+)\s(?<action>\w+)

[copycat:database]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_database_fields = (?<query_type>\w+)\squery\sexecuted\son\stable\s(?<table_name>\w+)\sby\suser\s(?<user>[\w\.]+)\s-\s(?<duration>\d+)ms

[copycat:system]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_system_fields = (?<process>\w+)\[(?<pid>\d+)\]:\s(?<message>.*)

[copycat:api]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_api_fields = (?<method>\w+)\s(?<path>(/\w+)+)\sfrom\s(?<ip>\d+\.\d+\.\d+\.\d+)\s-\sResponse:\s(?<http_status>\d+)\s-\s(?<duration>\d+)ms

[copycat:error]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_error_fields = (?<type>\w+)\sin\s(?<path>(/[\w\.]+)+):(?<line>\d+)\s-\s(?<message>.*)

[copycat:metrics]
TIME_FORMAT = %Y-%m-%d %T.%f
EXTRACT-copycat_metrics_fields = (?<resource>\w+)\susage:\s(?<usage_percentage>\d+)\%\s-\sHost:\s(?<target_host>[\w\.-]+)
