[copycat_app_indexed]
REGEX = ^\S+\s\S+\s\[(\w+)\]
FORMAT = copycat_level::$1
WRITE_META = true

[copycat_security_indexed]
REGEX = ^\S+\s\S+\sUser\s([\w\.]+)\s
FORMAT = copycat_user::$1
WRITE_META = true

[copycat_network_indexed]
REGEX = ^\S+\s\S+\s(\w+)\s\S+\s->\s\S+\s(\w+)
FORMAT = copycat_transport::$1 copycat_action::$2
WRITE_META = true

[copycat_docker_indexed]
REGEX = ^\S+\s\S+\sContainer\s\S+\s(\w+)
FORMAT = copycat_action::$1
WRITE_META = true

[copycat_database_indexed]
REGEX = ^\S+\s\S+\s(\w+)\squery\sexecuted
FORMAT = copycat_query_type::$1
WRITE_META = true

[copycat_system_indexed]
REGEX = ^\S+\s\S+\s(\w+)\[\d+\]:
FORMAT = copycat_process::$1
WRITE_META = true

[copycat_api_indexed]
REGEX = ^\S+\s\S+\s(\w+)\s\S+\sfrom\s\S+\s-\sResponse:\s(\d+)
FORMAT = copycat_method::$1 copycat_status::$2
WRITE_META = true

[copycat_error_indexed]
REGEX = ^\S+\s\S+\s(\w+)\sin\s
FORMAT = copycat_error_type::$1
WRITE_META = true

[copycat_metrics_indexed]
REGEX = ^\S+\s\S+\s(\w+)\susage:
FORMAT = copycat_resource::$1
WRITE_META = true
